apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: konflux-test-component-2
  namespace: amcdermo-tenant
  annotations:
    build.appstudio.openshift.io/build-nudge-files: nudge-files/component-1.sh
spec:
  application: konflux-test
  componentName: konflux-test-component-2
  source:
    git:
      url: https://github.com/frobware/konflux-test
      revision: main
      context: component-2