---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications
  - bpfapplicationstates
  - clusterbpfapplications
  - clusterbpfapplicationstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/finalizers
  - bpfapplicationstates/finalizers
  - clusterbpfapplications/finalizers
  - clusterbpfapplicationstates/finalizers
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/status
  - bpfapplicationstates/status
  - clusterbpfapplications/status
  - clusterbpfapplicationstates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalog.konflux.example.com
  resources:
  - testbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.konflux.example.com
  resources:
  - testbundles/finalizers
  verbs:
  - update
- apiGroups:
  - catalog.konflux.example.com
  resources:
  - testbundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: bpfman
rules:
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplicationstates
  verbs:
  - get
  - list
  - watch
